---
- name: Update apt-cache
  apt: update_cache=yes

- name: Install packages
  apt: pkg={{ item }}
  with_items:
    - python3
    - python3-pip
    - python-dev
    - python3-dev
    - python-pip
    - libxml2-dev
    - libxslt-dev
